### ISSUE TITLE
Position data doesn't get updated after timeout

### ISSUE THREAD

**Issue by BlackBadPinguin** [ReneNulschDE/mbapi2020#105]
Hello, unfortunately I noticed that sometimes the following error occurs and then the position tracker from the car is not updated until I restart Homeassistant. Other than that the integration is very good and works great, keep up the good work. :)
```
Logger: homeassistant
Source: custom_components/mbapi2020/websocket.py:128
Integration: MercedesME 2020 (documentation, issues)
First occurred: 21. Januar 2023 um 22:33:31 (1 occurrences)
Last logged: 21. Januar 2023 um 22:33:31

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/mbapi2020/websocket.py", line 128, in async_connect
    self._connection = await session.ws_connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 776, in _ws_connect
    resp = await self.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 893, in start
    with self._timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

```

**Comment by ReneNulschDE** [comment]
I tried multiple months to reproduce this without success - please share more details in a new issue when possible
