### ISSUE TITLE
keine Fahrzeugdaten werden als Entitäten angezeigt

### ISSUE THREAD

**Issue by Andreasroessler248** [ReneNulschDE/mbapi2020#149]
seit 10.11.2023 am morgen werden keine mehr angezeigt.

**Comment by ReneNulschDE** [comment]
das kann ich in meiner Umgebung nicht nachvollziehen. Was passiert genau? Welche Log EInträge gibt es im Debug Mode? Funktioniert die MB-App? Sind die Lizenzen noch gültig?

**Comment by Andreasroessler248** [comment]
Guten Morgen Herr Nulsch

 

Erst einmal vielen Dank dass Sie sich direkt melden.

 

Dann wird es wohl ein Problem auf meiner Seite sein.

 

Zu Ihren Fragen:

 

Jawohl die Mercedes Me App funktioniert am Handi und die Lizenzen sind gültig.

 

Im Debug Modus konnte ich folgende Daten finden, ich hoffe es hilft Ihnen weiter mein Problem einzugrenzen.

 

Für Sie zur Info: Ich betreibe home assistant auf einer Synology NAS als Docker Instantz.

 

 

 

Logger: homeassistant.config_entries

Source: config_entries.py:565

First occurred: 07:23:39 (5 occurrences)

Last logged: 07:23:39

 

Error unloading entry mbapi2020 for sensor

Error unloading entry mbapi2020 for lock

Error unloading entry mbapi2020 for binary_sensor

Error unloading entry mbapi2020 for device_tracker

Error unloading entry mbapi2020 for switch

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 565, in async_unload

    result = await component.async_unload_entry(hass, self)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 132, in async_unload_entry

    return await component.async_unload_entry(entry)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry

    raise ValueError("Config entry was never loaded!")

ValueError: Config entry was never loaded!

 

 

 

Vollständige LOG Datei ist wie folgt:

Ich habe einige Felder mit XXX demaskiert um persönliche Daten nicht zu veröffentlichen.

 

 

2023-11-11 07:21:56.975 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pyscript which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2023-11-11 07:21:56.976 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2023-11-11 07:21:56.977 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration mbapi2020 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2023-11-11 07:21:56.979 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_ac_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2023-11-11 07:21:56.980 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_dehumidifier_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2023-11-11 07:21:56.981 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration solcast_solar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2023-11-11 07:21:56.983 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2023-11-11 07:21:56.984 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration portainer which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2023-11-11 07:22:29.786 WARNING (MainThread) [homeassistant.setup] Setup of input_select is taking over 10 seconds.

2023-11-11 07:22:31.825 DEBUG (MainThread) [custom_components.mbapi2020.client] WSL not detected - running in rlock mode

2023-11-11 07:22:31.825 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()

2023-11-11 07:22:31.826 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()

2023-11-11 07:22:34.972 WARNING (MainThread) [homeassistant.config_entries] Config entry 'FRITZ!Box 7590 AX' for upnp integration not ready yet: Device not discovered: uuid:75802409-bccb-40e7-8e6c-3C37123EC18F::urn:schemas-upnp-org:device:InternetGatewayDevice:1; Retrying in background

2023-11-11 07:22:34.973 WARNING (MainThread) [homeassistant.config_entries] Config entry 'InternetGatewayDeviceV2 - FRITZ!Box 7590 AX' for upnp integration not ready yet: Device not discovered: uuid:75802409-bccb-40e7-9f6c-3C37123EC18F::urn:schemas-upnp-org:device:InternetGatewayDevice:2; Retrying in background

2023-11-11 07:22:36.158 DEBUG (MainThread) [custom_components.mbapi2020.client] start update_poll_states

2023-11-11 07:22:36.239 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()

2023-11-11 07:22:36.241 INFO (MainThread) [custom_components.mbapi2020.websocket] Connecting to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws

2023-11-11 07:22:37.610 INFO (MainThread) [custom_components.mbapi2020.websocket] Connected to mercedes websocket at wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws

2023-11-11 07:22:37.682 DEBUG (MainThread) [custom_components.mbapi2020.websocket] Got notification: debugMessage

2023-11-11 07:22:37.682 DEBUG (MainThread) [custom_components.mbapi2020.client] debugMessage - Data: Registering User with ciamID: 00110a0c094c8023 and App-UUID: 1480c542-0bcd-444f-b89e-8f7436c40eff

2023-11-11 07:22:37.682 DEBUG (MainThread) [custom_components.mbapi2020.websocket] Got notification: debugMessage

2023-11-11 07:22:37.682 DEBUG (MainThread) [custom_components.mbapi2020.client] debugMessage - Data: app twin actor was initialized

2023-11-11 07:22:44.087 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Automatisches Laden startet wenn Fahrzeug in Home Zone ankommt und elektrische Reichweiter < xx  km' trigger: In 'numeric_state' condition: unknown entity sensor.bb_fq_548_range_electric

2023-11-11 07:22:44.105 ERROR (MainThread) [homeassistant.components.automation.automatische_abschaltung_wenn_pv_leistung_weniger_als_250w_fur_10_minuten] Error setting up trigger Automatische Abschaltung E-Laden PV Produktion kleiner Wohnungsverbrauch

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/components/device_automation/trigger.py", line 64, in async_attach_trigger

    return await platform.async_attach_trigger(hass, config, action, trigger_info)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/device_tracker/device_trigger.py", line 90, in async_attach_trigger

    zone_config = await zone.async_validate_trigger_config(hass, zone_config)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/zone/trigger.py", line 55, in async_validate_trigger_config

    config[CONF_ENTITY_ID] = er.async_validate_entity_ids(

                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1380, in async_validate_entity_ids

    return [async_validate_entity_id(registry, item) for item in entity_ids_or_uuids]

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1380, in <listcomp>

    return [async_validate_entity_id(registry, item) for item in entity_ids_or_uuids]

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1349, in async_validate_entity_id

    raise vol.Invalid(f"Unknown entity registry entry {entity_id_or_uuid}")

voluptuous.error.Invalid: Unknown entity registry entry b76b1a41d25e0721922efc8e1cfa11d1

2023-11-11 07:22:44.141 ERROR (MainThread) [homeassistant.components.automation.automatischer_ladestart_soc_15] Error setting up trigger Automatisches Laden startet wenn Fahrzeug in Home Zone ankommt und elektrische Reichweiter < xx  km

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/components/device_automation/trigger.py", line 64, in async_attach_trigger

    return await platform.async_attach_trigger(hass, config, action, trigger_info)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/device_tracker/device_trigger.py", line 90, in async_attach_trigger

    zone_config = await zone.async_validate_trigger_config(hass, zone_config)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/zone/trigger.py", line 55, in async_validate_trigger_config

    config[CONF_ENTITY_ID] = er.async_validate_entity_ids(

                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1380, in async_validate_entity_ids

    return [async_validate_entity_id(registry, item) for item in entity_ids_or_uuids]

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1380, in <listcomp>

    return [async_validate_entity_id(registry, item) for item in entity_ids_or_uuids]

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1349, in async_validate_entity_id

    raise vol.Invalid(f"Unknown entity registry entry {entity_id_or_uuid}")

voluptuous.error.Invalid: Unknown entity registry entry b76b1a41d25e0721922efc8e1cfa11d1

2023-11-11 07:23:39.117 DEBUG (MainThread) [custom_components.mbapi2020] Start unload component.

2023-11-11 07:23:39.118 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry mbapi2020 for sensor

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 565, in async_unload

    result = await component.async_unload_entry(hass, self)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 132, in async_unload_entry

    return await component.async_unload_entry(entry)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry

    raise ValueError("Config entry was never loaded!")

ValueError: Config entry was never loaded!

2023-11-11 07:23:39.149 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry mbapi2020 for lock

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 565, in async_unload

    result = await component.async_unload_entry(hass, self)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 135, in async_unload_entry

    return await component.async_unload_entry(entry)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry

    raise ValueError("Config entry was never loaded!")

ValueError: Config entry was never loaded!

2023-11-11 07:23:39.161 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry mbapi2020 for binary_sensor

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 565, in async_unload

    result = await component.async_unload_entry(hass, self)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 175, in async_unload_entry

    return await component.async_unload_entry(entry)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry

    raise ValueError("Config entry was never loaded!")

ValueError: Config entry was never loaded!

2023-11-11 07:23:39.173 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry mbapi2020 for device_tracker

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 565, in async_unload

    result = await component.async_unload_entry(hass, self)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 81, in async_unload_entry

    return await component.async_unload_entry(entry)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry

    raise ValueError("Config entry was never loaded!")

ValueError: Config entry was never loaded!

2023-11-11 07:23:39.185 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry mbapi2020 for switch

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 565, in async_unload

    result = await component.async_unload_entry(hass, self)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/components/switch/__init__.py", line 89, in async_unload_entry

    return await component.async_unload_entry(entry)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry

    raise ValueError("Config entry was never loaded!")

ValueError: Config entry was never loaded!

2023-11-11 07:23:39.193 DEBUG (MainThread) [custom_components.mbapi2020] unload not successful.

2023-11-11 07:23:46.411 INFO (MainThread) [custom_components.mbapi2020.oauth] Start request ***@***.***

2023-11-11 07:24:00.198 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start _save_token_info() to /config/.mercedesme-token-cache

2023-11-11 07:24:00.204 DEBUG (MainThread) [custom_components.mbapi2020] Token received

2023-11-11 07:24:00.205 DEBUG (MainThread) [custom_components.mbapi2020.client] WSL not detected - running in rlock mode

2023-11-11 07:24:00.205 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()

2023-11-11 07:24:00.206 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()

2023-11-11 07:24:00.344 DEBUG (MainThread) [custom_components.mbapi2020.client] start update_poll_states

2023-11-11 07:24:00.356 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()

2023-11-11 07:24:00.358 INFO (MainThread) [custom_components.mbapi2020.websocket] Connecting to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws

2023-11-11 07:24:00.578 INFO (MainThread) [custom_components.mbapi2020.websocket] Connected to mercedes websocket at wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws

2023-11-11 07:24:00.579 DEBUG (MainThread) [custom_components.mbapi2020.websocket] Got notification: debugMessage

2023-11-11 07:24:00.580 DEBUG (MainThread) [custom_components.mbapi2020.client] debugMessage - Data: Registering User with ciamID: 00110a0c094c8023 and App-UUID: xxxxxee11-86e2-4d19-9ea8-50ecad48ad1f

2023-11-11 07:24:00.582 DEBUG (MainThread) [custom_components.mbapi2020.websocket] Got notification: debugMessage

2023-11-11 07:24:00.582 DEBUG (MainThread) [custom_components.mbapi2020.client] debugMessage - Data: app twin actor was initialized

2023-11-11 07:27:37.683 INFO (MainThread) [custom_components.mbapi2020.websocket] Watchdog expired – calling _disconnected

2023-11-11 07:27:37.683 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()

2023-11-11 07:27:37.684 INFO (MainThread) [custom_components.mbapi2020.websocket] Connecting to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws

2023-11-11 07:27:37.802 INFO (MainThread) [custom_components.mbapi2020.websocket] Connected to mercedes websocket at wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws

2023-11-11 07:27:37.807 DEBUG (MainThread) [custom_components.mbapi2020.websocket] Got notification: debugMessage

2023-11-11 07:27:37.807 DEBUG (MainThread) [custom_components.mbapi2020.client] debugMessage - Data: Registering User with ciamID: xxx10a0c094c8023 and App-UUID: xxxcfb50-63e3-4226-8cc7-39c7ab3d9a60

2023-11-11 07:27:37.809 DEBUG (MainThread) [custom_components.mbapi2020.websocket] Got notification: debugMessage

2023-11-11 07:27:37.809 DEBUG (MainThread) [custom_components.mbapi2020.client] debugMessage - Data: app twin actor was initialized

2023-11-11 07:29:00.583 INFO (MainThread) [custom_components.mbapi2020.websocket] Watchdog expired – calling _disconnected

2023-11-11 07:29:00.583 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()

2023-11-11 07:29:00.584 INFO (MainThread) [custom_components.mbapi2020.websocket] Connecting to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws

2023-11-11 07:29:00.700 INFO (MainThread) [custom_components.mbapi2020.websocket] Connected to mercedes websocket at wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws

2023-11-11 07:29:00.702 DEBUG (MainThread) [custom_components.mbapi2020.websocket] Got notification: debugMessage

2023-11-11 07:29:00.703 DEBUG (MainThread) [custom_components.mbapi2020.client] debugMessage - Data: Registering User with ciamID: 00110a0c094c8023 and App-UUID: xxx4ebf-b59a-42b0-85c3-53f4f49ada85

2023-11-11 07:29:00.704 DEBUG (MainThread) [custom_components.mbapi2020.websocket] Got notification: debugMessage

2023-11-11 07:29:00.704 DEBUG (MainThread) [custom_components.mbapi2020.client] debugMessage - Data: app twin actor was initialized

2023-11-11 07:32:37.809 INFO (MainThread) [custom_components.mbapi2020.websocket] Watchdog expired – calling _disconnected

2023-11-11 07:32:37.810 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()

2023-11-11 07:32:37.811 INFO (MainThread) [custom_components.mbapi2020.websocket] Connecting to wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws

2023-11-11 07:32:37.925 INFO (MainThread) [custom_components.mbapi2020.websocket] Connected to mercedes websocket at wss://websocket.emea-prod.mobilesdk.mercedes-benz.com/ws

2023-11-11 07:32:37.927 DEBUG (MainThread) [custom_components.mbapi2020.websocket] Got notification: debugMessage

2023-11-11 07:32:37.927 DEBUG (MainThread) [custom_components.mbapi2020.client] debugMessage - Data: Registering User with ciamID: 00110a0c094c8023 and App-UUID: xxxc6e6c-22d5-4721-838e-1e1177c827c3

2023-11-11 07:32:37.929 DEBUG (MainThread) [custom_components.mbapi2020.websocket] Got notification: debugMessage

2023-11-11 07:32:37.929 DEBUG (MainThread) [custom_components.mbapi2020.client] debugMessage - Data: app twin actor was initialized

 

 

Ich bedanke mich ganz herzlich bei Ihnen für Ihre Unterstützung und Ihre Zeit.

 

Liebe Grüße

 

Andreas Rössler

 

 

Von: Rene Nulsch ***@***.***> 
Gesendet: Samstag, 11. November 2023 06:59
An: ReneNulschDE/mbapi2020 ***@***.***>
Cc: Andreasroessler248 ***@***.***>; Author ***@***.***>
Betreff: Re: [ReneNulschDE/mbapi2020] keine Fahrzeugdaten werden als Entitäten angezeigt (Issue #149)

 

das kann ich in meiner Umgebung nicht nachvollziehen. Was passiert genau? Welche Log EInträge gibt es im Debug Mode? Funktioniert die MB-App? Sind die Lizenzen noch gültig?

**Comment by ReneNulschDE** [comment]
Danke. Sieht so aus als werden für den Account keine registrierten Cars zurückgegeben von MB. Ich würde emfehlen erstmal folgendes zu tun:

1. Beenden von Home Assistant (HA)
2. Löschen der Datei .mercedesme-token-cache im Config-Ordner von HA
3. Neustarten von HA
4. Es kommt eine Warnung (Task) im Frontend, dass die MBAPI2020 Komponente neu anmelden muß. Diese Schritte ausführen
5. Testen

Wenn das nicht funktioniert:
1. Die Option "DEBUG ONLY: Enable save server messages to the messages folder" im Konfiguration Dialog der Komponente aktivieren
2. Die Funktion "Enable Debug Logging" auf der Übersichtsseite der Integration anklicken
3. HA Neu starten
4. 2min warten
5. Die Option "DEBUG ONLY: Enable save server messages to the messages folder" im Konfiguration Dialog der Komponente deaktivieren
6. Die Option "Disable debug logging" auf der Übersichtsseite der Integration anklicken und die Datei speichern, die zum Download angeboten wird
7. Alle Dateien im Order **HA-Config-Folder**/custom_components/mbapi2020/messages in ein Archiv verpacken
8. Die Dateien von Punkt 6 und 7 per mail an mbdev.issue-149@nulsch.de schicken

**Comment by Master-Osiris** [comment]
I had the same issue but was able to resolve the problem with your hint to delete the .mercedesme-token-cache!
Thanks for the support, great app :)

**Comment by ReneNulschDE** [comment]
Solved via email (token cache file deleted)
