### ISSUE TITLE
 Error requesting: https://bff.emea-prod.mobilesdk.mercedes-benz.com/v2/vehicles - 418 - 0 -

### ISSUE THREAD

**Issue by Sweti934** [ReneNulschDE/mbapi2020#232]
### The problem

Mercedes Me Integration is completely offline ("Unavailable").

The report in the logs saym:
`Logger: custom_components.mbapi2020.webapi
Quelle: custom_components/mbapi2020/webapi.py:115
Integration: MercedesME 2020 ([Dokumentation](https://github.com/ReneNulschDE/mbapi2020), [Probleme](https://github.com/ReneNulschDE/mbapi2020/issues))
Erstmals aufgetreten: 15:38:19 (2 Vorkommnisse)
Zuletzt protokolliert: 16:03:58
Error requesting: https://bff.emea-prod.mobilesdk.mercedes-benz.com/v2/vehicles - 418 - 0 -`

### What version of MBAPI2020 do use?

v0.14.0-beta.1

### What was the last working version of MBAPI2020?

v0.14.0-beta.1

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

2024-05-28 15:38:19.525 ERROR (MainThread) [custom_components.mbapi2020.webapi] Error requesting: https://bff.emea-prod.mobilesdk.mercedes-benz.com/v2/vehicles - 418 - 0 - 
2024-05-28 15:38:19.525 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ABCD@gmail.com (Region: Europe) for mbapi2020
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 584, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mbapi2020/__init__.py", line 77, in async_setup_entry
    for car in masterdata.get("assignedVehicles"):
               ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

### Anything in the logs that might be useful for us?

```txt
Not really, everything was working fine until today all of a sudden!
```

**Comment by Sweti934** [comment]
see here https://github.com/ReneNulschDE/mbapi2020/issues/231
