### ISSUE TITLE
MercedesMe 2020 App not loading in HA

### ISSUE THREAD

**Issue by Max6993109** [ReneNulschDE/mbapi2020#256]
### The problem

The App seemed to stopped working.  It now tries to initialize, but times out.  I tried deleting the whole thing and re-downloading and still encounter the same issue.  See error code below: 

Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 1:24:03 AM (1 occurrences)
Last logged: 1:24:03 AM

Error setting up entry +19172970655 (Region: North America) for mbapi2020
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mbapi2020/__init__.py", line 184, in async_setup_entry
    await asyncio.sleep(0.5)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

### What version of MBAPI2020 do use?

v0.16.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

Logger: homeassistant.config_entries
Source: config_entries.py:586
First occurred: 1:24:03 AM (1 occurrences)
Last logged: 1:24:03 AM

Error setting up entry +19172970655 (Region: North America) for mbapi2020
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mbapi2020/__init__.py", line 184, in async_setup_entry
    await asyncio.sleep(0.5)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

**Comment by ReneNulschDE** [comment]
Do you have registered cars in this account? If yes, please send me an email to mbdev.us-load@nulsch.de then we can discuss more options as I don't have access to a car in the US.

**Comment by ReneNulschDE** [comment]
Wrong account used, solved via email
