### ISSUE TITLE
Problem setting up account after backup restore - "Unknown Error Occurred" in configuration

### ISSUE THREAD

**Issue by rEegLer** [ReneNulschDE/mbapi2020#277]
### The problem

Upgraded to RPi5 and restored from backup of HA. Had to reconfigure all of my custom components. I'm quite that the integration had stopped working a couple days ago prior to the upgrade because the dedicated display I created for the car did not update the SOC, range, etc. info for my EQS. When I tried to reconfigure the integration, I get the "unknown error occurred" error and I cannot go any further.
![Screenshot 2024-11-17 143606](https://github.com/user-attachments/assets/9d25a728-c592-4698-ab8d-646d5b96b12a)

### What version of MBAPI2020 do use?

v0.19.1

### What was the last working version of MBAPI2020?

v0.19.0

### What type of installation are you running?

Home Assistant OS

### Diagnostics information

I've deleted the integration multiple times, done system resets, all to no avail.  I've checked the closed issues and none are directly related to my issue with the current version. 

### Anything in the logs that might be useful for us?

```txt
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:448
First occurred: 2:25:36 PM (1 occurrences)
Last logged: 2:25:36 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 567, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/Mb-bkp/config_flow.py", line 66, in async_step_user
    await client.oauth.request_pin(user_input[CONF_USERNAME], nonce)
  File "/config/custom_components/Mb-bkp/oauth.py", line 68, in request_pin
    return await self._async_request("post", url, data=data, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/Mb-bkp/oauth.py", line 242, in _async_request
    raise err
  File "/config/custom_components/Mb-bkp/oauth.py", line 238, in _async_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1158, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 418, message="I'm a teapot", url='https://bff.amap-prod.mobilesdk.mercedes-benz.com/v1/login'
```

**Comment by ReneNulschDE** [comment]
The error 418 I'm a Teapot - is a clear indicator that you have not the latest version 0.19.x.
The component is loaded from /config/custom_components/Mb-bkp/? normally the path is mbapi2020... Do you have an old copy in this folder?

I just tested the onboarding in the US and I got a PIN.
