### ISSUE TITLE
Error setting up entry mbapi2020 for mbapi2020

### ISSUE THREAD

**Issue by Valiceemo** [ReneNulschDE/mbapi2020#34]
Updated Home Assistant to version 2021.12.10 and the integration no longer wrorks.

grabs from log:
```
Traceback (most recent call last):
  File "/config/custom_components/mbapi2020/api.py", line 73, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://bff-prod.risingstars.daimler.com/v1/vehicle/self/masterdata')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/mbapi2020/__init__.py", line 118, in async_setup_entry
    masterdata = await mercedes.client.api.get_user_info()
  File "/config/custom_components/mbapi2020/api.py", line 83, in get_user_info
    return await self._request("get", "/v1/vehicle/self/masterdata")
  File "/config/custom_components/mbapi2020/api.py", line 76, in _request
    raise RequestError(f"Error requesting data from {url}: {err}")
custom_components.mbapi2020.errors.RequestError: Error requesting data from https://bff-prod.risingstars.daimler.com/v1/vehicle/self/masterdata: 404, message='Not Found', url=URL('https://bff-prod.risingstars.daimler.com/v1/vehicle/self/masterdata')

```
```
2022-01-19 12:17:01 ERROR (MainThread) [homeassistant.components.system_health] Error fetching info
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 68, in get_integration_info
data = await registration.info_callback(hass)
File "/config/custom_components/mbapi2020/system_health.py", line 21, in system_health_info
client = hass.data[DOMAIN]
KeyError: 'mbapi2020'
```

**Comment by Valiceemo** [comment]
closing this
integration was updated, but i forgot to restart home assistant. 
apologies
