### ISSUE TITLE
404 - https://bff-prod.risingstars.daimler.com/v1/vehicle/self/masterdata

### ISSUE THREAD

**Issue by tarrinho** [ReneNulschDE/mbapi2020#38]
Hello,

updated yesterday the plugin for the homeassistant, and I'm getting:
********************************************
Error setting up entry mbapi2020 for mbapi2020

Traceback (most recent call last):
  File "/config/custom_components/mbapi2020/api.py", line 73, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL('https://bff-prod.risingstars.daimler.com/v1/vehicle/self/masterdata')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 313, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/mbapi2020/__init__.py", line 118, in async_setup_entry
    masterdata = await mercedes.client.api.get_user_info()
  File "/config/custom_components/mbapi2020/api.py", line 83, in get_user_info
    return await self._request("get", "/v1/vehicle/self/masterdata")
  File "/config/custom_components/mbapi2020/api.py", line 76, in _request
    raise RequestError(f"Error requesting data from {url}: {err}")
custom_components.mbapi2020.errors.RequestError: Error requesting data from https://bff-prod.risingstars.daimler.com/v1/vehicle/self/masterdata: 404, message='Not Found', url=URL('https://bff-prod.risingstars.daimler.com/v1/vehicle/self/masterdata')
********************************************

Please help!

Thanks

**Comment by tarrinho** [comment]
Sorry, my bad.

![image](https://user-images.githubusercontent.com/1039120/152358926-078c67df-1c97-4679-b8c5-c2e50149d71d.png)

**Comment by tarrinho** [comment]
Just updated and it works!
