### ISSUE TITLE
I'm a teapot?

### ISSUE THREAD

**Issue by Dario82** [ReneNulschDE/mbapi2020#77]
Hello,
I received this error when I trying the integration configuration...

Logger: aiohttp.server
Source: custom_components/mbapi2020/oauth.py:240
Integration: MercedesME 2020 (documentation, issues)
First occurred: 15:54:10 (8 occurrences)
Last logged: 17:30:15

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/mbapi2020/config_flow.py", line 74, in async_step_user
    await client.oauth.request_pin(user_input[CONF_USERNAME], nonce)
  File "/config/custom_components/mbapi2020/oauth.py", line 62, in request_pin
    return await self._async_request("post", url, data=data, headers=headers )
  File "/config/custom_components/mbapi2020/oauth.py", line 244, in _async_request
    raise err
  File "/config/custom_components/mbapi2020/oauth.py", line 240, in _async_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 418, message="I'm a teapot", url=URL('https://bff-prod.risingstars.daimler.com/v1/login')

**Comment by ReneNulschDE** [comment]
Hi, thanks for reporting. I can reproduce the error. Looks like MB has changed the Authentication Backend. Let me check.

**Comment by ReneNulschDE** [comment]
I have published a new version v0.6.9 - this will solve this. Background: MB changed the minimum app version and I had to adjust the version number in my code

**Comment by Bamboooo67** [comment]
Thanks for the quick correction 👍🏻
