### ISSUE TITLE
Unknown Error Occurred in configuration

### ISSUE THREAD

**Issue by dustin05** [ReneNulschDE/mbapi2020#78]
I noticed in the last day or two that my mbapi2020 integration had stopped working.  I've tried to  reload, restart, etc. before removing the integration and re-adding it.  Entering my email, choosing North America, and clicking submit I get a red "Unknown Error Occurred".  I've tried to post a screenshot below with the email changed.  I did use a valid email.

Here's more info from the error.  Let me know what else I can provide:

This error originated from a custom integration.

Logger: custom_components.mbapi2020.oauth
Source: custom_components/mbapi2020/oauth.py:62 
Integration: MercedesME 2020 (documentation, issues) 
First occurred: 5:47:17 PM (1 occurrences) 
Last logged: 5:47:17 PM

ClientError requesting data from https://bff-prod.risingstars-amap.daimler.com/v1/login: 418, message="I'm a teapot", url=URL('https://bff-prod.risingstars-amap.daimler.com/v1/login')

<img width="534" alt="image" src="https://user-images.githubusercontent.com/22064334/203437174-4f6d3d84-8a70-486e-9520-69c935a8c5e1.png">

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/mbapi2020/oauth.py:240 
Integration: MercedesME 2020 (documentation, issues) 
First occurred: 5:47:17 PM (1 occurrences) 
Last logged: 5:47:17 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/mbapi2020/config_flow.py", line 74, in async_step_user
    await client.oauth.request_pin(user_input[CONF_USERNAME], nonce)
  File "/config/custom_components/mbapi2020/oauth.py", line 62, in request_pin
    return await self._async_request("post", url, data=data, headers=headers )
  File "/config/custom_components/mbapi2020/oauth.py", line 244, in _async_request
    raise err
  File "/config/custom_components/mbapi2020/oauth.py", line 240, in _async_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 418, message="I'm a teapot", url=URL('https://bff-prod.risingstars-amap.daimler.com/v1/login')

**Comment by dustin05** [comment]
Never mind I see you just patched this.  I'll close it but will follow up if it didn't work for me for some reason.  Thank you!

**Comment by dustin05** [comment]
Never mind.  I updated and still see the above errors.  I posted in the HA forum, so I won't reopen this issue here.

**Comment by yestrdave** [comment]
Dustin, 
Did you ever figure this issue out?

**Comment by ReneNulschDE** [comment]
Hi, this should be fixed with the new version v0.6.10. This includes the fix for the US-region.
