### ISSUE TITLE
Can not log in. Unknown Error

### ISSUE THREAD

**Issue by yestrdave** [ReneNulschDE/mbapi2020#79]
Home Assistant 2022.11.4
Supervisor 2022.10.2
Operating System 9.3
Frontend 20221108.0 - latest
![image](https://user-images.githubusercontent.com/93943061/203451969-e91e7e19-5225-4736-8341-398bfe5637e5.png)
Logger: aiohttp.server
Source: custom_components/mbapi2020/oauth.py:240
Integration: MercedesME 2020 ([documentation](https://github.com/ReneNulschDE/mbapi2020), [issues](https://github.com/ReneNulschDE/mbapi2020/issues))
First occurred: 8:11:37 PM (1 occurrences)
Last logged: 8:11:37 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/mbapi2020/config_flow.py", line 74, in async_step_user
    await client.oauth.request_pin(user_input[CONF_USERNAME], nonce)
  File "/config/custom_components/mbapi2020/oauth.py", line 62, in request_pin
    return await self._async_request("post", url, data=data, headers=headers )
  File "/config/custom_components/mbapi2020/oauth.py", line 244, in _async_request
    raise err
  File "/config/custom_components/mbapi2020/oauth.py", line 240, in _async_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 418, message="I'm a teapot", url=URL('https://bff-prod.risingstars-amap.daimler.com/v1/login')

**Comment by yestrdave** [comment]
![image](https://user-images.githubusercontent.com/93943061/203452751-eed78fd9-d21f-4f57-8ae7-7190986a55b1.png)

**Comment by ReneNulschDE** [comment]
Hi, this should be fixed with the new version v0.6.10.

**Comment by yestrdave** [comment]
Thank you Rene.  Fixed
