### ISSUE TITLE
Unauthorized (401) api calls on new installation

### ISSUE THREAD

**Issue by rujudk** [ReneNulschDE/mbapi2020#83]
Hi

I had your excellent component working on an old HA installation but that installation is now dead.
I am now running a test HA in Oracle cloud and did a new installation of HA where I installed mbapi2020 using HACS.
During setup, only 1 out of 4 cars is found. When adding the car the component fails to call MB API successfully

```
2022-11-24 21:01:03.640 INFO (MainThread) [custom_components.mbapi2020.client] WSL not detected - running in rlock mode
2022-11-24 21:01:03.640 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-11-24 21:01:03.641 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-11-24 21:01:03.988 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-11-24 21:01:04.214 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-11-24 21:01:04.540 DEBUG (MainThread) [custom_components.mbapi2020] RCP supported for car **VIN**: True
2022-11-24 21:01:04.540 DEBUG (MainThread) [custom_components.mbapi2020] Init - car added - **VIN**
2022-11-24 21:01:04.540 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-11-24 21:01:04.621 DEBUG (MainThread) [custom_components.mbapi2020.api] Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/mbapi2020/api.py", line 86, in _request
    resp.raise_for_status()
  File "/srv/homeassistant/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 401, message='Unauthorized', url=URL('https://bff-prod.risingstars.daimler.com/v1/vehicle/**VIN**/capabilities/commands')

2022-11-24 21:01:04.621 WARNING (MainThread) [custom_components.mbapi2020] Can't connect to MB APIs; Retrying in background
```

I have tried removing .mercedesme-token-cache, the component itself, cleaned HACS, and reinstalled mbapi2020 with the same result.

I tried using the cached access token in Postman and successfully called https://bff-prod.risingstars.daimler.com/v2/vehicles which returns all four cars.
https://bff-prod.risingstars.daimler.com/v1/vehicle/**VIN**/capabilities/commands return 401 unauthorized in postman too.

Keep up the good work!

**Comment by rujudk** [comment]
I have 4 cars on my Mercedes Me account. 1 of them does not have the communications module installed due to the global components shortage

It turns out the failing API call is that car. Replacing the VIN with the three others I have all work just fine.

The car added to HA is the first entry in the output from /v2/vehicles. The second is the failing one.

**Comment by ReneNulschDE** [comment]
Thanks for reporting, this is solved in the master branch now and will be part of the next release 0.7.5.
