### ISSUE TITLE
mbapi2020 Stopped to work - Still Retrying setup

### ISSUE THREAD

**Issue by bobofruit1970** [ReneNulschDE/mbapi2020#91]
This integration worked for me for over the year.
Yesterday upgraded and today it is not working.

Uninstalled all and installed again.

Installation goes like always

First in HACS, then ADD integration.

Integration asked me for e-mail. I write an e-mail and choosed as a REGION - EUROPE.  Integration showed message "Unknown error occured" 
![Capture223](https://user-images.githubusercontent.com/67933104/208463562-2182774a-a6a0-447d-a8c8-14232b55dcbf.PNG)

I did the same and choose as a Region - North America 
Integration asked for pin from e-mail. 
For a few seconds I get an e-mail with PIN

![Capture225](https://user-images.githubusercontent.com/67933104/208463635-37d5df82-4561-4954-affe-e17c1f016663.PNG)

I put PIN from en e-mail I get from mercedes and Integration confirmed configuration created.

![Capture227](https://user-images.githubusercontent.com/67933104/208463672-87aaf1c2-0024-4034-9b34-e190de089051.PNG)

 
At this moment always everything should start to work. But it did not. Restart does not help. Installation previous version of integration or delete of token file does not help.

Integration still trying to connect and it fails.

![image](https://user-images.githubusercontent.com/67933104/208465859-18765066-85bb-4d3b-a4f1-da79834d155b.png)

![image](https://user-images.githubusercontent.com/67933104/208468014-9a3a95aa-e5a7-4dbd-89ff-40029df53a6c.png)

System log shows:

2022-12-19 16:26:46.307 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration mbapi2020 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-12-19 16:27:03.179 INFO (MainThread) [custom_components.mbapi2020.client] WSL not detected - running in rlock mode
2022-12-19 16:27:03.179 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:27:03.182 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:27:05.631 DEBUG (MainThread) [custom_components.mbapi2020.api] Traceback (most recent call last):
File "/config/custom_components/mbapi2020/api.py", line 86, in _request
resp.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 418, message="I'm a teapot", url=URL('https://bff.amap-prod.mobilesdk.mercedes-benz.com/v2/vehicles')
2022-12-19 16:27:05.631 WARNING (MainThread) [custom_components.mbapi2020] Can't connect to MB APIs; Retrying in background
2022-12-19 16:27:05.638 WARNING (MainThread) [homeassistant.config_entries] Config entry 'mbapi2020' for mbapi2020 integration not ready yet; Retrying in background
2022-12-19 16:27:10.749 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_car.attributes.last_message_received | default("1971-01-01 00:00:00") }}'
2022-12-19 16:27:10.757 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ states.sensor.wa7114a_car.attributes.last_message_received | default("1971-01-01 00:00:00") }}")
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 423, in async_render
render_result = _render_with_context(self.template, compiled, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1942, in _render_with_context
return template.render(**kwargs)
File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 1, in top-level template code
File "/usr/local/lib/python3.10/site-packages/jinja2/sandbox.py", line 326, in getattr
value = getattr(obj, attribute)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1968, in _fail_with_undefined_error
raise ex
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1959, in _fail_with_undefined_error
return super()._fail_with_undefined_error(*args, **kwargs)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 540, in async_render_to_info
render_info._result = self.async_render(variables, strict=strict, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 425, in async_render
raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
2022-12-19 16:27:10.760 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_car.attributes.last_message_received | default("1971-01-01 00:00:00") }}'
2022-12-19 16:27:10.763 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{{ states.sensor.wa7114a_car.attributes.last_message_received | default("1971-01-01 00:00:00") }}")' for attribute '_attr_native_value' in entity 'sensor.car_status_update'
2022-12-19 16:27:10.767 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_starter_battery_state.attributes.value_short | default("wait") }}'
2022-12-19 16:27:10.769 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template("{{ states.sensor.wa7114a_starter_battery_state.attributes.value_short | default("wait") }}")
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 423, in async_render
render_result = _render_with_context(self.template, compiled, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1942, in _render_with_context
return template.render(**kwargs)
File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
self.environment.handle_exception()
File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
raise rewrite_traceback_stack(source=source)
File "<template>", line 1, in top-level template code
File "/usr/local/lib/python3.10/site-packages/jinja2/sandbox.py", line 326, in getattr
value = getattr(obj, attribute)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1968, in _fail_with_undefined_error
raise ex
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1959, in _fail_with_undefined_error
return super()._fail_with_undefined_error(*args, **kwargs)
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 540, in async_render_to_info
render_info._result = self.async_render(variables, strict=strict, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 425, in async_render
raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
2022-12-19 16:27:10.772 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_starter_battery_state.attributes.value_short | default("wait") }}'
2022-12-19 16:27:10.775 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template("{{ states.sensor.wa7114a_starter_battery_state.attributes.value_short | default("wait") }}")' for attribute '_attr_native_value' in entity 'sensor.car_soc'
2022-12-19 16:27:10.887 INFO (MainThread) [custom_components.mbapi2020.client] WSL not detected - running in rlock mode
2022-12-19 16:27:10.887 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:27:10.893 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:27:10.984 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Komunikat "zatankuj samochód"' trigger: In 'numeric_state' condition: unknown entity sensor.wa7114a_fuel_level
2022-12-19 16:27:11.036 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Komunikat "zatankuj samochód"' trigger: In 'numeric_state' condition: unknown entity sensor.wa7114a_fuel_level
2022-12-19 16:27:11.058 WARNING (MainThread) [homeassistant.components.homeassistant.triggers.numeric_state] Error initializing 'Komunikat "zatankuj samochód"' trigger: In 'numeric_state' condition: unknown entity sensor.wa7114a_fuel_level
2022-12-19 16:27:16.644 DEBUG (MainThread) [custom_components.mbapi2020.api] Traceback (most recent call last):
File "/config/custom_components/mbapi2020/api.py", line 86, in _request
resp.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 418, message="I'm a teapot", url=URL('https://bff.amap-prod.mobilesdk.mercedes-benz.com/v2/vehicles')
2022-12-19 16:27:16.644 WARNING (MainThread) [custom_components.mbapi2020] Can't connect to MB APIs; Retrying in background
2022-12-19 16:27:26.647 INFO (MainThread) [custom_components.mbapi2020.client] WSL not detected - running in rlock mode
2022-12-19 16:27:26.648 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:27:26.651 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:27:27.395 DEBUG (MainThread) [custom_components.mbapi2020.api] Traceback (most recent call last):
File "/config/custom_components/mbapi2020/api.py", line 86, in _request
resp.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 418, message="I'm a teapot", url=URL('https://bff.amap-prod.mobilesdk.mercedes-benz.com/v2/vehicles')
2022-12-19 16:27:27.395 WARNING (MainThread) [custom_components.mbapi2020] Can't connect to MB APIs; Retrying in background
2022-12-19 16:27:47.401 INFO (MainThread) [custom_components.mbapi2020.client] WSL not detected - running in rlock mode
2022-12-19 16:27:47.401 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:27:47.404 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:27:48.157 DEBUG (MainThread) [custom_components.mbapi2020.api] Traceback (most recent call last):
File "/config/custom_components/mbapi2020/api.py", line 86, in _request
resp.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 418, message="I'm a teapot", url=URL('https://bff.amap-prod.mobilesdk.mercedes-benz.com/v2/vehicles')
2022-12-19 16:27:48.158 WARNING (MainThread) [custom_components.mbapi2020] Can't connect to MB APIs; Retrying in background
2022-12-19 16:28:10.838 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_car.attributes.last_message_received | default("1971-01-01 00:00:00") }}'
2022-12-19 16:28:10.843 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_starter_battery_state.attributes.value_short | default("wait") }}'
2022-12-19 16:28:28.162 INFO (MainThread) [custom_components.mbapi2020.client] WSL not detected - running in rlock mode
2022-12-19 16:28:28.162 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:28:28.168 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:28:28.919 DEBUG (MainThread) [custom_components.mbapi2020.api] Traceback (most recent call last):
File "/config/custom_components/mbapi2020/api.py", line 86, in _request
resp.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 418, message="I'm a teapot", url=URL('https://bff.amap-prod.mobilesdk.mercedes-benz.com/v2/vehicles')
2022-12-19 16:28:28.919 WARNING (MainThread) [custom_components.mbapi2020] Can't connect to MB APIs; Retrying in background
2022-12-19 16:29:10.844 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_car.attributes.last_message_received | default("1971-01-01 00:00:00") }}'
2022-12-19 16:29:10.850 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_starter_battery_state.attributes.value_short | default("wait") }}'
2022-12-19 16:29:48.925 INFO (MainThread) [custom_components.mbapi2020.client] WSL not detected - running in rlock mode
2022-12-19 16:29:48.926 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:29:48.927 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:29:49.674 DEBUG (MainThread) [custom_components.mbapi2020.api] Traceback (most recent call last):
File "/config/custom_components/mbapi2020/api.py", line 86, in _request
resp.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 418, message="I'm a teapot", url=URL('https://bff.amap-prod.mobilesdk.mercedes-benz.com/v2/vehicles')
2022-12-19 16:29:49.674 WARNING (MainThread) [custom_components.mbapi2020] Can't connect to MB APIs; Retrying in background
2022-12-19 16:30:10.848 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_car.attributes.last_message_received | default("1971-01-01 00:00:00") }}'
2022-12-19 16:30:10.853 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_starter_battery_state.attributes.value_short | default("wait") }}'
2022-12-19 16:31:09.681 INFO (MainThread) [custom_components.mbapi2020.client] WSL not detected - running in rlock mode
2022-12-19 16:31:09.681 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:31:09.683 DEBUG (MainThread) [custom_components.mbapi2020.oauth] Start async_get_cached_token()
2022-12-19 16:31:10.421 DEBUG (MainThread) [custom_components.mbapi2020.api] Traceback (most recent call last):
File "/config/custom_components/mbapi2020/api.py", line 86, in _request
resp.raise_for_status()
File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 418, message="I'm a teapot", url=URL('https://bff.amap-prod.mobilesdk.mercedes-benz.com/v2/vehicles')
2022-12-19 16:31:10.422 WARNING (MainThread) [custom_components.mbapi2020] Can't connect to MB APIs; Retrying in background
2022-12-19 16:31:10.850 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_car.attributes.last_message_received | default("1971-01-01 00:00:00") }}'
2022-12-19 16:31:10.856 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_starter_battery_state.attributes.value_short | default("wait") }}'
2022-12-19 16:32:10.864 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_car.attributes.last_message_received | default("1971-01-01 00:00:00") }}'
2022-12-19 16:32:10.869 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.sensor.wa7114a_starter_battery_state.attributes.value_short | default("wait") }}'

**Comment by ReneNulschDE** [comment]
Hi, I just published a bugfix release v0.7.1 to handle the changes on MB-API side.

**Comment by bobofruit1970** [comment]
Thank You very much.
Everything works now.
![image](https://user-images.githubusercontent.com/67933104/208476924-1b58c318-7270-408d-8722-308b6c5eb038.png)

**Comment by raespanha** [comment]
Hey @bobofruit1970 
Can I ask how can I get a similar car card? it looks awesome!

**Comment by bobofruit1970** [comment]
Here You are.
When You open car picture in any app it will look strange because it is transparent. In HA it will look like below.

![mercnew5](https://user-images.githubusercontent.com/67933104/208746873-4915a6a0-e897-4658-91b6-8e7ccc4672f0.png)

Save car picture to raspberry image directory eg. (right mouse button on below picture and select option "save image as ..." )

config\www\images\mercnew5.png

Add CARD as a "Picture Elements" and show car picture mercnew5.png according to below configuration file.
At the end of configuration You will find path to car picture
You will have to change entities names to Yours entities names and modify config to Your car . If Your car has rear doors you will have to add rear door locks entities in config. My car is coupe so there are only rear windows in my config. 

``
type: picture-elements
elements:
  - entity: sensor.car_status_update
    style:
      transform: translate(-50%, -50%) scale(0.8, 0.8)
      color: lightgrey
      left: 15%
      top: 92%
    type: state-label
  - entity: lock.wa7114a_lock
    type: state-icon
    tap-action:
      action: toggle
    icon: mdi:car-door
    name: Door locks
    style:
      transform: translate(-50%, -50%) scale(1.3, 1.3)
      color: lightgrey
      left: 67%
      top: 60%
  - entity: sensor.car_soc
    style:
      transform: translate(-50%, -50%) scale(0.9, 0.9)
      color: lightgrey
      left: 57.5%
      top: 18%
    type: state-label
  - entity: sensor.wa7114a_fuel_level
    prefix: ''
    suffix: ''
    style:
      transform: translate(-50%, -50%) scale(0.9, 0.9)
      color: lightgrey
      left: 5%
      top: 17%
    type: state-label
  - entity: sensor.car_rangeliquid
    prefix: ''
    suffix: ' km'
    style:
      transform: translate(-50%, -50%) scale(0.9, 0.9)
      color: lightgrey
      left: 19%
      top: 17%
    type: state-label
  - entity: sensor.wa7114a_odometer
    prefix: ' '
    suffix: ' '
    style:
      transform: translate(-50%, -50%) scale(0.9, 0.9)
      color: lightgrey
      left: 34%
      top: 17%
    type: state-label
  - entity: sensor.car_daystoservice
    prefix: ' '
    suffix: ' '
    style:
      transform: translate(-50%, -50%) scale(.7, .7)
      color: lightgrey
      left: 43%
      top: 5%
    type: state-label
  - entity: binary_sensor.wa7114a_tire_warning
    prefix: ''
    style:
      transform: translate(-50%, -50%) scale(0.7, 0.7)
      color: '#FFFFFF'
      left: 66.5%
      top: 17.5%
    type: state-icon
  - entity: binary_sensor.wa7114a_low_brake_fluid_warning
    prefix: ''
    style:
      transform: translate(-50%, -50%) scale(0.7, 0.7)
      color: '#FFFFFF'
      left: 76%
      top: 17.5%
    type: state-icon
  - entity: binary_sensor.wa7114a_low_wash_water_warning
    prefix: ''
    style:
      transform: translate(-50%, -50%) scale(0.7, 0.7)
      color: '#FFFFFF'
      left: 95%
      top: 17.5%
    type: state-icon
  - entity: binary_sensor.wa7114a_low_coolant_level_warning
    prefix: ''
    style:
      transform: translate(-50%, -50%) scale(0.7, 0.7)
      color: '#FFFFFF'
      left: 85%
      top: 17.5%
    icon: mdi:car-coolant-level
    type: state-icon
  - entity: sensor.car_tire_pressure_front_right
    style:
      transform: translate(-50%, -50%) scale(0.8, 0.8)
      color: lightgrey
      left: 38%
      top: 32%
    type: state-label
  - entity: sensor.car_tire_pressure_rear_right
    style:
      transform: translate(-50%, -50%) scale(0.8, 0.8)
      color: lightgrey
      left: 84%
      top: 32%
    type: state-label
  - entity: sensor.car_tire_pressure_front_left
    style:
      transform: translate(-50%, -50%) scale(0.7, 0.7)
      color: lightgrey
      left: 38%
      top: 90%
    type: state-label
  - entity: sensor.car_tire_pressure_rear_left
    style:
      transform: translate(-50%, -50%) scale(0.8, 0.8)
      color: lightgrey
      left: 84%
      top: 90%
    type: state-label
  - entity: sensor.car_lock_front_right
    style:
      '--paper-item-icon-color': white
      transform: translate(-50%, -50%) scale(0.7, 0.7)
      left: 61%
      top: 38%
    type: state-icon
  - entity: sensor.car_lock_front_left
    style:
      '--paper-item-icon-color': white
      transform: translate(-50%, -50%) scale(0.7, 0.7)
      left: 61%
      top: 83%
    type: state-icon
  - entity: sensor.car_lock_trunk
    style:
      '--paper-item-icon-color': white
      transform: translate(-50%, -50%) scale(0.7, 0.7)
      left: 91%
      top: 60%
    type: state-icon
  - entity: sensor.car_window_front_right
    style:
      '--paper-item-icon-color': lightgrey
      transform: translate(-50%, -50%) scale(0.7, 0.7)
      left: 56%
      top: 31%
    type: state-icon
  - entity: sensor.car_window_rear_right
    style:
      '--paper-item-icon-color': lightgrey
      transform: translate(-50%, -50%) scale(0.7, 0.7)
      left: 73%
      top: 31%
    type: state-icon
  - entity: sensor.car_window_front_left
    style:
      '--paper-item-icon-color': lightgrey
      transform: translate(-50%, -50%) scale(0.7, 0.7)
      left: 56%
      top: 90%
    type: state-icon
  - entity: sensor.car_window_rear_left
    style:
      '--paper-item-icon-color': lightgrey
      transform: translate(-50%, -50%) scale(0.7, 0.7)
      left: 73%
      top: 90%
    type: state-icon
  - entity: binary_sensor.wa7114a_park_brake_status
    prefix: ''
    style:
      transform: translate(-50%, -50%) scale(0.8, 0.8)
      color: '#FFFFFF'
      left: 13%
      top: 43%
    type: state-icon
  - entity: sensor.car_windows_status
    prefix: ''
    style:
      transform: translate(-50%, -50%) scale(0.8, 0.8)
      color: lightgrey
      left: 17%
      top: 53%
    type: state-label
  - entity: sensor.car_lock_status
    prefix: ''
    style:
      transform: translate(-50%, -50%) scale(0.8, 0.8)
      color: lightgrey
      left: 14%
      top: 64%
    type: state-label
  - entity: device_tracker.wa7114a_device_tracker
    prefix: ''
    style:
      color: lightgrey
      left: 13%
      top: 77%
    type: state-label
image: local/images/mercnew5.png
``

**Comment by raespanha** [comment]
Thanks so much!
